# Generated by Django 2.2.16 on 2022-11-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221125_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttorecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredienttorecipe', to='app.Recipe'),
        ),
    ]
